### ISSUE TITLE
ChineseSimplified

### ISSUE THREAD

**Issue by HawnHan** [ritsu/RimFlix#5]
Hello, I am sorry to talk to you in this way, because I am not familiar with GitHub. I really like your mod, it adds fun to RIMWORLD. For the love of MOD, I made a simplified Chinese translation of MOD. I hope you can adopt it and let MOD be accepted by more Chinese. (My English is not good, but you can use the translation file with confidence. This is a Google translation.)
[ChineseSimplified.zip](https://github.com/ritsu/RimFlix/files/3211230/ChineseSimplified.zip)

**Comment by ritsu** [comment]
Thank you very much for the translation! I have updated both the GitHub release and the Steam Workshop release. 谢谢！

**Comment by HawnHan** [comment]
You are harder than me, I sincerely thank you for your selfless dedication.

ritsu <notifications@github.com> 于2019年6月3日周一 上午8:48写道：
